version: '3.6'

volumes:
  database:
  node_modules:

services:
  database:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - database:/var/lib/mysql

  wordpress:
    image: wordpress:5.6.0-php7.4
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    ports:
      - ${PORT_WORDPRESS}:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: define('FS_METHOD', 'direct');
    volumes:
      - ./docker/config/php:/etc/php/conf.d:ro,cached
      - ./docker/logs/apache2:/var/log/apache2
      - ./plugins:/var/www/html/plugins
      - ${WORDPRESS_THEME_LOCATION}:/var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}:ro,cached
      - ./docker/volumes/wordpress/wp-content:/var/www/html/wp-content:cached
    depends_on:
      - database

  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    ports:
      - ${PORT_ADMINER}:8080
    links:
      - database
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    ports:
      - ${PORT_PHPMYADMIN}:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_ABSOLUTE_URI: http://${DOMAIN}/_pma/
      PMA_HOST: database
    links:
      - database
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - wordpress
      - adminer
      - phpmyadmin

  composer:
    image: composer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ${WORDPRESS_THEME_LOCATION}:/var/www/html/theme
    depends_on:
      - wordpress

  wpcli:
    image: wordpress:cli
    container_name: ${COMPOSE_PROJECT_NAME}_wpcli
    working_dir: /var/www/html
    user: xfs
    volumes_from:
      - wordpress
    links:
      - database
      - wordpress
    depends_on:
      - database
      - wordpress

